minimal_mistakes_skin: contrast
locale: ko-KR
title: 안녕하세요.
title_separator: '|'
subtitle: 어서오세요. 환영합니다. | Welcome, y'all! Come on in.
name: Shin Dong-Hyeon
description: 즐기다 가세요.
url: https://dongkoony.github.io
repository: null
teaser: null
masthead_title: null
breadcrumbs: true
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: dongkoony
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
  utterances:
    theme: null
    issue_term: null
  giscus:
    repo_id: null
    category_name: null
    category_id: null
    discussion_term: null
    reactions_enabled: null
    theme: null
  staticman:
    branch: null
    endpoint: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
  hide: null
search: false
search_full_content: false
search_provider: false
lunr:
  search_within_pages: false
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
naver_site_verification: 481bdea1101d4b74214dd5687f380dfd8c57f48e
yandex_site_verification: null
baidu_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: google-gtag
  google:
    tracking_id: G-99SSB6GL03
    anonymize_ip: false
author:
  name: Shin Dong-Hyeon
  avatar: /assets/images/emoji.png
  bio: 차린 건 없지만, 즐기다 가세요.
  location: South Korea of Seoul
  email: shin.dh922@gmail.com
  links:
    - label: linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/donghyeon-shin-a037a926b/
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/dongkoony
    - label: Website
      icon: fas fa-fw fa-link
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
    - label: Instagram
      icon: fab fa-fw fa-instagram
footer:
  links:
    - label: linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/donghyeon-shin-a037a926b/
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/dongkoony
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
    - label: GitLab
      icon: fab fa-fw fa-gitlab
    - label: Bitbucket
      icon: fab fa-fw fa-bitbucket
    - label: Instagram
      icon: fab fa-fw fa-instagram
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: /:title/ # /:categories/:title/ 
paginate: 5
paginate_path: /page:num/
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 추가
data_dir: _data

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    category_permalink: /:name/
    tag: /tags/:name/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ""
      type: pages #posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_sticky: true
      toc_label: Contents
      toc_icon: fa-solid fa-ghost
      
date_format: '%Y-%m-%d'
dark_theme_toggle: true
after_footer_scripts:
  - /assets/js/custom/dark-theme.js
collections:
  splash:
    output: true  
  aws:
    output: true
    permalink: /aws/:path/
  python:
    output: true
    permalink: /python/:path/
  terraform:
    output: true
    permalink: /terraform/:path/
  linux:
    output: true
    permalink: /linux/:path/
Resources:
  Account:
    Type: AWS::ApiGateway::Account
    Properties: {}