version: '3.3'
services:
  mop-doc:
    image: netfoundry/mop-api-docs
    build:
      context: .
    volumes:
      - .:/site
    ports:
      - 4000:4000
    environment:
      - JEKYLL_GITHUB_TOKEN
