name: Your Workflow Name
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@bf91c7e87bbf8be60165a97dd46b245f76a18289
        with:
          repo-token: ${{ secrets.my_token_blog_pull_request  }}
          configuration-path: .github/labeler.yml
          sync-labels: ''
