name: Close Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Close Pull Request
        uses: peter-evans/close-pull-request@v3
        with:
          repo-token: ${{ secrets.MY_REPO_TOKEN }}
