name: 라벨링

on:
  pull_request:
    types:
      - opened

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - name: 라벨 적용
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['Type: Invalid']
            });
