name: Close Pull Request

on:
  pull_request_target:
    types:
      - opened

jobs:
  close_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        uses: peter-evans/close-pull-request@v1
        with:
          repo-token: ${{ secrets.MY_GITHUB_BLOG_TOKEN_PULL_REQUEST }}
          delete-branch: true # PR의 기능 브랜치를 삭제하려면 true로 설정하십시오.
