name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # 또는 귀하의 대상 브랜치

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/actions/jekyll-build-pages:v1.0.9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and deploy
      env:
        JEKYLL_ENV: production
      run: |
        jekyll build
        touch ./_site/.nojekyll
