name: Labeler

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v3
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.MY_GITHUB_BLOG_TOKEN_PULL_REQUEST }}
          sync-labels: true
        if: github.event.pull_request.merged == true

  
