name: Labeler

on:
  # 액션을 실행할 트리거 이벤트 (여기서는 pull request)
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  apply-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Labeler
      uses: actions/labeler@v3
      with:
        configuration-path: .github/labeler.yml
        repo-token: ${{ secrets.MY_GITHUB_BLOG_TOKEN_PULL_REQUEST }}
