name: Labeler

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: 워크플로 시작
        uses: some_action@v1
        with:
          repo-token: ${{ MY_GITHUB_BLOG_TOKEN_PULL_REQUEST }}

