name: Labeler

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]

jobs:
  # Issue 및 Pull Request의 라벨 관리 작업을 수행합니다.
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Labeler
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  # Pull Request가 병합되었을 경우 해외 PR에 해당하는 브랜치를 삭제하고, 해당 PR을 닫습니다.
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Labeler
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.MY_GITHUB_BLOG_TOKEN_PULL_REQUEST }}
        if: github.event.pull_request.merged == true
