name: Labeler

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: 라벨러 실행
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml # 라벨 설정 파일경로
          sync-labels: true 


