name: Pull request labeler
on:
  - pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: My Action Step
      uses: some-owner/some-action@v1
      with:
        repo-token: ${{ secrets.my_token_blog_pull_request  }}
