# Build settings
markdown: kramdown
theme: minima
plugins: ['jekyll/scholar']

scholar:
  style: modern-language-association
  sort_by: author
  group_by: year
  group_order: descending

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
